# Generated by Django 4.2.9 on 2024-01-06 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0005_subjects_subjectmarks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subjects',
            new_name='Subject',
        ),
    ]
